global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'checkout-service'
    static_configs:
      - targets: ['host.docker.internal:5297']
    metrics_path: /metrics

  - job_name: 'shipping-promise-service'
    static_configs:
      - targets: ['host.docker.internal:5237']
    metrics_path: /metrics

  - job_name: 'order-service'
    static_configs:
      - targets: ['host.docker.internal:5279']
    metrics_path: /metrics

  - job_name: 'shipment-service'
    static_configs:
      - targets: ['host.docker.internal:5194']
    metrics_path: /metrics

  - job_name: 'tracking-service'
    static_configs:
      - targets: ['host.docker.internal:5200']
    metrics_path: /metrics

  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:5206']
    metrics_path: /metrics

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['host.docker.internal:5168']
    metrics_path: /metrics

  - job_name: 'fulfillment-center-service'
    static_configs:
      - targets: ['host.docker.internal:5039']
    metrics_path: /metrics

  - job_name: 'routing-service'
    static_configs:
      - targets: ['host.docker.internal:5099']
    metrics_path: /metrics

  - job_name: 'carrier-service'
    static_configs:
      - targets: ['host.docker.internal:5247']
    metrics_path: /metrics

  - job_name: 'shipping-pricing-service'
    static_configs:
      - targets: ['host.docker.internal:5197']
    metrics_path: /metrics

  - job_name: 'product-catalog-service'
    static_configs:
      - targets: ['host.docker.internal:5009']
    metrics_path: /metrics

  - job_name: 'order-visibility-service'
    static_configs:
      - targets: ['host.docker.internal:48930']
    metrics_path: /metrics
