global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'checkout-service'
    static_configs:
      - targets: ['host.docker.internal:5001']
    metrics_path: /metrics

  - job_name: 'shipping-promise-service'
    static_configs:
      - targets: ['host.docker.internal:5002']
    metrics_path: /metrics

  - job_name: 'order-service'
    static_configs:
      - targets: ['host.docker.internal:5003']
    metrics_path: /metrics

  - job_name: 'shipment-service'
    static_configs:
      - targets: ['host.docker.internal:5004']
    metrics_path: /metrics

  - job_name: 'tracking-service'
    static_configs:
      - targets: ['host.docker.internal:5005']
    metrics_path: /metrics

  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:5006']
    metrics_path: /metrics

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['host.docker.internal:5007']
    metrics_path: /metrics

  - job_name: 'fulfillment-center-service'
    static_configs:
      - targets: ['host.docker.internal:5008']
    metrics_path: /metrics

  - job_name: 'routing-service'
    static_configs:
      - targets: ['host.docker.internal:5009']
    metrics_path: /metrics

  - job_name: 'carrier-service'
    static_configs:
      - targets: ['host.docker.internal:5010']
    metrics_path: /metrics

  - job_name: 'shipping-pricing-service'
    static_configs:
      - targets: ['host.docker.internal:5011']
    metrics_path: /metrics

  - job_name: 'product-catalog-service'
    static_configs:
      - targets: ['host.docker.internal:5012']
    metrics_path: /metrics

  - job_name: 'audit-service'
    static_configs:
      - targets: ['host.docker.internal:5013']
    metrics_path: /metrics
